### ISSUE TITLE
Issue in finetuning gpt2 model

### ISSUE THREAD

**Issue by Aaryanverma** [Pan-ML/panml#59]
while finetuning gpt2 model, getting this error:
```IndexError: index out of range in self```

**Comment by Aaryanverma** [comment]
Here is the code:
```
lm = ModelPack(model='gpt2', source='huggingface')
# Specify train args
train_args = {
    'title': 'gpt2',
    'num_train_epochs' : 2,
    'mlm': False,
    'optimizer': 'adamw_torch',
    'per_device_train_batch_size': 1,
    'per_device_eval_batch_size': 1,
    'warmup_steps': 0,
    'weight_decay': 0.01,
    'logging_steps': 10,
    'output_dir': './results',
    'logging_dir': './logs',
    'save_model': True,
}

# Prepare data
x = df['input_text']
y = df['target_text']

# Train model
lm.fit(x, y, train_args, instruct=True)

**Comment by wanoz** [comment]
Ah I see. Yup I get it.

Check out the training GPT2 part here:
https://github.com/Pan-ML/panml/wiki/3.-Fine-tuning-your-LLM

Check the second section on GPT2 training. GPT2 is a trained differently to FLAN, in non-instruct based method (instruct=False, and y and x are set to be the same, since it's self supervised).

**Comment by Aaryanverma** [comment]
ok got it. Thanks for clarifying.

**Comment by Aaryanverma** [comment]
After following the instructions for gpt, still getting same error

**Comment by wanoz** [comment]
So do you get the error during the lm.fit process? Like during training? I'm thinking could it be due to missing or null data somewhere. It seems to work okay for me on my end:
<img width="795" alt="image" src="https://github.com/Pan-ML/panml/assets/23420089/ff60fc5a-4297-45b3-b37a-1f13f0b5f25a">

**Comment by wanoz** [comment]
Ok let me investigate it. What is the dataset you're using? Is it an open source dataset I can check as well?

**Comment by Aaryanverma** [comment]
No, this is a private dataset, cannot share here for obvious reasons. Dataset includes a very long text with instruction, context and response headings inside the string text.

**Comment by wanoz** [comment]
Oh interesting. I suspect it's a context window thing or somehow the tokenizer is not recognising some characters. I will investigate this through a simulated dataset but this is my current line of thinking.

**Comment by wanoz** [comment]
Just an update @Aaryanverma, the issue here is due to the model having a max context tokens length of typically 512-1024 tokens. If we want to use them in our training, we will need to truncate or split up the sequence so that each context sequence is no more than 1024 (GPT2's max length is 1024, other models have different max sequence length, for e.g. Flan-T5 has 512 I believe). 

For enhancement, I will make an update so it displays the max context tokens length when the model is first loaded. Thanks for bring this to attention.

**Comment by Aaryanverma** [comment]
Ok but this never happened with flan models, they worked perfectly fine with longer sequences. Is it related to GPT like architectures only?
